
name: backpack_buddy_json_persist
description: A Flutter project with JSON checklist and SharedPreferences.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  slider_button: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/checklist.json
