
name: backpack_buddy_json_persist
description: A Flutter project with JSON checklist and SharedPreferences.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true
  assets:
    - assets/checklist.json
